name: shop_app_flutter
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  flutter_svg: ^0.18.1
  provider: ^4.3.2+1

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/apple-pay.png
    - assets/images/fedex-express.png
    - assets/images/glap.png
    - assets/images/google-pay.png
    - assets/images/Image Banner 2.png
    - assets/images/Image Banner 3.png
    - assets/images/Image Popular Product 1.png
    - assets/images/Image Popular Product 2.png
    - assets/images/Image Popular Product 3.png
    - assets/images/mastercard-2.png
    - assets/images/Pattern Success.png
    - assets/images/paypal.png
    - assets/images/product 1 image.png
    - assets/images/Profile Image.png
    - assets/images/ps4_console_blue_1.png
    - assets/images/ps4_console_blue_2.png
    - assets/images/ps4_console_blue_3.png
    - assets/images/ps4_console_blue_4.png
    - assets/images/ps4_console_white_1.png
    - assets/images/ps4_console_white_2.png
    - assets/images/ps4_console_white_3.png
    - assets/images/ps4_console_white_4.png
    - assets/images/shoes2.png
    - assets/images/splash_1.png
    - assets/images/splash_2.png
    - assets/images/splash_3.png
    - assets/images/success.png
    - assets/images/tshirt.png
    - assets/images/visa.png
    - assets/images/wireless headset.png
    - assets/icons/arrow_right.svg
    - assets/icons/Back ICon.svg
    - assets/icons/Bell.svg
    - assets/icons/Bill Icon.svg
    - assets/icons/Call.svg
    - assets/icons/Camera Icon.svg
    - assets/icons/Cart Icon.svg
    - assets/icons/Cash.svg
    - assets/icons/Chat bubble Icon.svg
    - assets/icons/Check mark rounde.svg
    - assets/icons/Close.svg
    - assets/icons/Conversation.svg
    - assets/icons/Discover.svg
    - assets/icons/Error.svg
    - assets/icons/facebook-2.svg
    - assets/icons/Flash Icon.svg
    - assets/icons/Game Icon.svg
    - assets/icons/Gift Icon.svg
    - assets/icons/google-icon.svg
    - assets/icons/Heart Icon.svg
    - assets/icons/Heart Icon_2.svg
    - assets/icons/Location point.svg
    - assets/icons/Lock.svg
    - assets/icons/Log out.svg
    - assets/icons/Mail.svg
    - assets/icons/Parcel.svg
    - assets/icons/Phone.svg
    - assets/icons/Plus Icon.svg
    - assets/icons/Question mark.svg
    - assets/icons/receipt.svg
    - assets/icons/remove.svg
    - assets/icons/Search Icon.svg
    - assets/icons/Settings.svg
    - assets/icons/Shop Icon.svg
    - assets/icons/Star Icon.svg
    - assets/icons/Success.svg
    - assets/icons/Trash.svg
    - assets/icons/twitter.svg
    - assets/icons/User.svg
    - assets/icons/User Icon.svg
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Muli
      fonts:
        - asset: assets/fonts/muli/Muli.ttf
        - asset: assets/fonts/muli/Muli-Bold.ttf
          weight: 700
        - asset: assets/fonts/muli/Muli-Light.ttf
          weight: 300
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
